services:
  # jsDelivr Proxy 服务
  jsdelivr-proxy:
    image: ghcr.io/liueic/jsdelivr-proxy:latest
    container_name: jsdelivr-proxy
    ports:
      - "8080:8080"  # 映射到8080端口
    environment:
      - PORT=8080
      - BASE_URL=https://cdn.jsdelivr.net
      - CACHE_DIR=/app/cache
      - CACHE_TTL=604800         # 7天
      - MEMORY_CACHE_TTL=7200    # 2小时
      - MAX_FILE_SIZE=52428800   # 50MB
      - NODE_ENV=production